### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by gjain0** [omarish/django-cprofile-middleware#10]
in django 1.10.6, I got this error after inserting middleware at last index.

```
  File "/t/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

**Comment by faost** [comment]
You need to change 

```python
class ProfilerMiddleware(object):
```

to 

```python
from django.utils.deprecation import MiddlewareMixin
class ProfilerMiddleware(MiddlewareMixin):
```

Here is pull request #11

**Comment by alizain** [comment]
@omarish, it'd be great if you could release a new version with this fix, I'd like not to install the HEAD

**Comment by yarax** [comment]
still there :(

**Comment by omarish** [comment]
This is fixed in https://github.com/omarish/django-cprofile-middleware/releases/tag/v1.0.

**Comment by MD-ARMAN-Shanto** [comment]
> You need to change
> 
> ```python
> class ProfilerMiddleware(object):
> ```
> 
> to
> 
> ```python
> from django.utils.deprecation import MiddlewareMixin
> class ProfilerMiddleware(MiddlewareMixin):
> ```
> 
> Here is pull request #11

thank you bro
