### ISSUE TITLE
Support of django 1.8.

### ISSUE THREAD

**Issue by hobbestigrou** [omarish/django-cprofile-middleware#15]
Currently the project don't support django 1.8. The project use MiddlewareMixin come with django 1.10. Django 1.8 is still used I would to know if you are ok to add the support of this django version.

**Comment by omarish** [comment]
Sure - want to open up a PR that does this? I'd like to stick to using `MiddlewareMixin` where possible, but we can always fallback to support versions of Django before 1.10 without the mixin.
