### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by bryan-woods** [omarish/django-cprofile-middleware#21]
pip install django-cprofile-middleware
Collecting django-cprofile-middleware
  Using cached https://files.pythonhosted.org/packages/3b/c2/0cb878b0018b54444849d4569c6b36e0688eb1316e363e356228bb5d1b0f/django-cprofile-middleware-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c4/8qchc1vj479_9v7h_xm8ztw5hj2xk1/T/pip-install-UPHoZq/django-cprofile-middleware/setup.py", line 10, in <module>
        with open(path.join(project_path, 'README.md')) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/c4/8qchc1vj479_9v7h_xm8ztw5hj2xk1/T/pip-install-UPHoZq/django-cprofile-middleware/README.md'

**Comment by omarish** [comment]
Fixing now.

**Comment by omarish** [comment]
Fixed in v1.0.4. Could you give it a try?

https://pypi.org/project/django-cprofile-middleware/1.0.4/

**Comment by bryan-woods** [comment]
Works thanks.
