### ISSUE TITLE
Can't install v0.2 from pip

### ISSUE THREAD

**Issue by golmansax** [omarish/django-cprofile-middleware#9]
When I do `pip install django-cprofile-middleware`, it installs v0.1.  Looks like the newest version is missing from https://pypi.python.org/simple/django-cprofile-middleware/.

**Comment by omarish** [comment]
Hey @golmansax, sorry about that. I just pushed v0.4 which should fix this issue.

**Comment by golmansax** [comment]
@omarish Thanks!
